name: goliath
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3+4
  sqflite: ^1.1.6
  dio: 3.0.3
  english_words: ^3.1.3
  json_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/tan.jpg
    - images/codewars.jpg
    - images/codewars_content.png